#!/usr/bin/env bash
# Host snapshot for wiki-lint-watch (L1). Report-only.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
DATE="$(date -u +%Y-%m-%d)"
OUT="reports/loops/${DATE}-wiki-lint-host.md"
mkdir -p reports/loops
{
  echo "# Wiki lint host snapshot — ${DATE}"
  echo
  echo "Generated by \`scripts/loop-wiki-lint-host.sh\` (L1 report-only)."
  echo
  echo '```'
  python3 scripts/wiki_lint_check.py 2>&1 || true
  echo '```'
  echo
  echo '## JSON'
  echo
  echo '```json'
  python3 scripts/wiki_lint_check.py --json 2>&1 || true
  echo '```'
} >"$OUT"
echo "wrote ${OUT}"
