#!/usr/bin/env python3
"""
qa-report-helper.py
Small helper for qa-agent.

Usage (via ddev exec):
  python3 .grok/skills/qa-agent/scripts/qa-report-helper.py --ensure-dir
  python3 .grok/skills/qa-agent/scripts/qa-report-helper.py --skeleton "pre-pr" --date 2026-06-28
  python3 .grok/skills/qa-agent/scripts/qa-report-helper.py --dry --scope "recent changes"

Features:
- Ensures reports/qa/ directory
- Generates dated skeleton report (markdown)
- Dry-run mode for simulation without side effects
- Reusable across projects (project-specific bits are minimal)
"""

import argparse
import os
from datetime import datetime
from pathlib import Path

REPORTS_DIR = Path("reports/qa")

def ensure_dir():
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Ensured directory: {REPORTS_DIR}")

def generate_skeleton(scope: str, date_str: str | None = None):
    ensure_dir()
    if not date_str:
        date_str = datetime.now().strftime("%Y-%m-%d")
    safe_scope = "".join(c if c.isalnum() or c in "-_" else "_" for c in scope)[:50]
    filename = f"{date_str}-qa-{safe_scope}.md"
    path = REPORTS_DIR / filename

    content = f"""# QA Report — {scope} — {date_str}

**Scope:** {scope}
**Date:** {date_str}
**Verdict:** READY | CONDITIONAL | BLOCKED   <!-- fill after run -->

## Summary
<!-- 2-4 sentences -->

## Checklist Results
### General
- [ ] Cache loaded (manifest + CONCERNS + CONVENTIONS + TESTING)
- [ ] Safety gates passed (ddev + test DB)
- [ ] Functional correctness verified
- [ ] Test adequacy reviewed
- [ ] Maintainability / structural review
- [ ] Verified outcomes (not just code)

### Project Specializations
- [ ] Load the correct references/<project>-specializations.md for the wave target (facebook-stats, google-stats, e-ndsign, ndestates-io, lightstone, ...)
- [ ] Domain risks from the chosen specialization followed
- [ ] High-churn script regression coverage
- [ ] Reports/ artifacts hygiene (no commit of generated CSVs)
- [ ] Cache discipline & token usage

## Key Evidence
<!-- commands run, file:line, test output, subagent results -->

## Issues
### Critical
### High
### Medium / Low

## Sign-off
**Verdict:** 
**Conditions / Blockers:**
**Recommendations:**
**Cache cited:** 
**Handoff token:** qa: {scope} VERDICT=... ; report={path}

<!-- Generated by qa-report-helper.py (dry or real) -->
"""

    path.write_text(content)
    print(f"Generated skeleton: {path}")
    return path

def dry_run(scope: str):
    print("=== DRY RUN: qa-agent simulation ===")
    print(f"Scope: {scope}")
    print("Loading cache-first (simulated): manifest, CONCERNS, CONVENTIONS, TESTING, TODO")
    print("Running general checklist (simulated)...")
    print("Running project specializations (via references/*-specializations.md for the wave project)...")
    print("Simulating test-safety + relevant tests via ddev exec (dry)")
    print("Verdict would be: READY (or CONDITIONAL/BLOCKED based on real run)")
    print("Would write report to reports/qa/")
    ensure_dir()
    print("Dry run complete. Use --skeleton to generate template, then fill with real /qa-agent run.")

def main():
    parser = argparse.ArgumentParser(description="qa-agent helper script")
    parser.add_argument("--ensure-dir", action="store_true", help="Ensure reports/qa exists")
    parser.add_argument("--skeleton", type=str, metavar="SCOPE", help="Generate skeleton report for SCOPE")
    parser.add_argument("--date", type=str, help="Override date YYYY-MM-DD")
    parser.add_argument("--dry", action="store_true", help="Dry-run simulation of qa-agent")
    parser.add_argument("--scope", type=str, default="general", help="Scope for dry run")
    args = parser.parse_args()

    if args.ensure_dir:
        ensure_dir()
    elif args.skeleton:
        generate_skeleton(args.skeleton, args.date)
    elif args.dry:
        dry_run(args.scope)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
